//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Recordid { get; set; }
        public string Cartid { get; set; }
        public int Albumid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
